import "./style.css";
import { addNewProject } from "./addProject";
import projectSwitchLogic from "./projectSwitchLogic";
import renderProjects from "./renderProjects";
import addTaskForm from "./addTasks";
import renderTasks from "./renderTasks";
import deleteTask from "./deleteTask";
import taskComplete from "./taskComplete";
import clickedDelBtn from "./projectDelete";
import taskEditDOM from "./editBtn";
import { loadState } from "./storage";

loadState();
renderProjects();
renderTasks();
addTaskForm();
addNewProject();
projectSwitchLogic();
deleteTask();
taskEditDOM();
clickedDelBtn();
taskComplete();
